### ISSUE TITLE
Audience Tab Changes

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#3]
-	Inside the tab next to the image, could we add a little more space above where the paragraph starts so that the paragraph and “learn more” text are a little more centered with the picture? I know this will change with how much text we have, so even just a little more space above the paragraph would be sufficient

**Comment by joelworsham** [comment]
This seems to be addressed in issue #9, so I will close this issue, but make sure this is resolved in #9.
