### ISSUE TITLE
News/Events Section changes

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#4]
-	Please make the weight of the events/alumni spotlight/student spotlight the same as the “Jackson College News” but take it down a point size or two. We like the gold color.
-	Could we add the shadowed lines on either side of the “Jackson College news” section and add more air around each picture/paragrph? We would like the styling to resemble the News/Events section at www.wm.edu. 
-	I like the side of the headlines, but could we take down the point size of the text underneath each of the headlines a point size?
-	At the end of the alumni/student spotlight, instead of the [. . . ] could we have it say “Read more …” in the same color as the headline and bold (like the news/events section at www.wm.edu)

**Comment by joelworsham** [comment]
I'm gathering, from this issue and others, that it might be a good idea to drop the main paragraph font size down a bit. I will go ahead and do this and that should help with some other issues as well.

**Comment by banksashleym** [comment]
Thanks!
