### ISSUE TITLE
Search Results page

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#6]
-	Could we remove the heading “Search results for:” in the burgundy bar? I don't think that needs to be there
- Could we remove the gray side navigation bar and have the results more centered in the content area?

**Comment by joelworsham** [comment]
I would recommend having some sort of page title. After navigating the site, the users will become accustomed to seeing the page title there and knowing where they are at. This is an excellent way for people to keep a handle on where in the site they are. I'm open to alternate ideas though.

That is a widgetized area, so we could add anything into that bar we like. We could even get creative with it and have it be a filter for search result content types or something. But, in the end if you don't want it there, I can definitely remove it.

**Comment by banksashleym** [comment]
Agree :) Maybe we could just call it "Search"?

**Comment by joelworsham** [comment]
Sure thing!
