### ISSUE TITLE
Mobile version of audience tabs

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/JC_Theme#9]
For the audience tabs-
-as I shrink the screen to the second smaller version with the tabs to the left and the content to the right. Could we add more space before the paragraph so it is more centered in the gray box? and add a little more padding around the whole paragraph/learn more link so that it's not so close to the edge of the box?

- for the smallest version of the audience tabs with the gray boxes on top of each other: Can we make it so the "future" and "students" is all on the same line (but keep the styling) and then left align the "future students", the paragraph and the "learn more" link. 

- please make the "learn more" link the same size as the two bigger versions before it.

**Comment by joelworsham** [comment]
I don't quite understand what you mean by:

please make the "learn more" link the same size as the two bigger versions before it.

**Comment by banksashleym** [comment]
In the full desktop version, the size of the "learn more" link is small, and when it's in mobile version the text size jumps up to be the same size as the "future students" header. Could we have it remain the small size (the size that it is in the desktop version)?

**Comment by joelworsham** [comment]
Oh right okay. Yes, I made it bigger on mobile on purpose, so it's easier for people to click it on a smaller screen, so it's a more prominent CTA. Though I can change it to small.
